config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'sandbox/clients'

  get 'sandbox/projects'

  get 'sandbox/products'
  get 'say/listing_products'
  get 'say/goodbye'
  get 'say/hello'

  get '/sandbox/get_jobs'
  get '/sandbox/zomato'

  resources :clients
  resources :projects
  resources :tasks

   root 'projects#index'

end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end

  def goodbye
  end

  def listing_products
  end
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/say/goodbye.html.erb
<h2>Goodbye World</h2>

<%= link_to "Hello World", "/say/hello", target: "_blank" %><br>

<%= link_to "Visit Hello World", say_hello_path %>

<p><code>say_hello_path</code> : this is linked to say hello path</p>

app/views/say/hello.html.erb
<h2>Hello World</h2>
<p>2 + 2 = <%=2 + 2 %></p>

<% name = "Suresh" %>
<p>Welcome to the site <%= name %></p>
<% movies = ["The Fury", "Departed", "Sully", "The Shooter"] %>
<h3>Listing movies</h3>
<ol>
	<% movies.each do |movie| %>
		<li><%= movie %></li>
	<% end %>
</ol>

<a href="http://www.google.com" target="_blank">Visit Google</a><br>

<%= link_to "Goodbye World", "/say/goodbye", target: "_blank" %><br>

<%= link_to "Visit Goodbye World", say_goodbye_path %>

app/views/say/listing_products.html.erb
<!-- Multiple comment line -->
<h2>Listing Products</h2>
<% products = {"pen" => 25, "scale" => 10, "pencil" => 15, "marker" => 25 } %>
<table border="1">
	<thead>
		<tr>
			<th>NAME	</th>
			<th>PRICE</th>
		</tr>
	</thead>
	<% sum = 0 %>
	<tbody>
		<% products.each do |product, price| %>
		<tr>
			<td><%= product.capitalize %></td>
			<td><%= price %></td>
		</tr>
		<% sum += price %>
		<% end %>
	</tbody>
</table>
<b>Total = <%= sum %></b><br>

<b>Total(inject) = <%= products.values.inject(:+) %></b>	