config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'sandbox/clients'

  get 'sandbox/projects'

  get 'sandbox/products'
  get 'say/listing_products'
  get 'say/goodbye'
  get 'say/hello'

  get '/sandbox/get_jobs'
  get '/sandbox/zomato'

  resources :clients
  resources :projects
  resources :tasks

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks

	has_many :project_categories
	has_many :categories, through: :project_categories


	belongs_to :client
	belongs_to :user

	validates_presence_of :name
	#validates_presence_of :client_id
	#validates_uniqueness_of :name
	validates_length_of :description, minimum: 10

	validate :check_status_on_create, on: :create
	validate :check_start_date, on: :create
	validate :check_client_project_count, on: :create
	validate :check_uniqueness_of_name, on: :create


	def completed_tasks
		self.tasks.where('is_completed = ?', true) 
	end

	def incompleted_tasks
		self.tasks.where('is_completed = ?', false)
	end

	def over_due_tasks
		self.tasks.where('is_completed = ? and due_date < ?', false, Date.today)
	end

	private

	def check_status_on_create
		if self.status != "new"
			errors.add(:status, " is not new")
		end
	end

	def check_start_date
		if !(self.start_date.nil?) && (self.start_date > Date.today + 1.week)
			errors.add(:start_date, " is invalid")
		end
	end

	def check_client_project_count
		project_count = Project.where('client_id = ?', self.client_id).count
		if project_count >= 2
			errors.add(:client_id, " already has 2 projects")
		end
	end


	def check_uniqueness_of_name

		project_names = Project.pluck('name')
		if project_names.include?(self.name)
			errors.add(:name, "already exist")
		end
	end
=begin

		if !(Project.where('name = ?', self.name).nil?)
			errors.add(:name, "already exist")
		end	
=end




end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authenticate_user!

	def index
		@projects = current_user.projects
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_param)
		@project.user_id = current_user.id
		if @project.save
			redirect_to project_path(@project), notice: "Successfully created" 
		else
			render action: "new"
		end
	end

	def show
		@project = current_user.projects.find(params[:id])
		@task = Task.new
	end

	def edit 
		begin
			@project = current_user.projects.find(params[:id])
		rescue ActiveRecord::RecordNotFound 
			redirect_to projects_path, notice: "Record not found"
		end
	end

	def update
		begin
			@project = current_user.projects.find(params[:id])
		rescue ActiveRecord::RecordNotFound 
			redirect_to projects_path, notice: "Record not found"
		end
		if @project.update_attributes(project_param)
			redirect_to project_path(@project), notice: "successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		begin
			@project = current_user.projects.find(params[:id])
		rescue ActiveRecord::RecordNotFound 
			redirect_to projects_path, notice: "Record not found"
		end
		@project.destroy
		redirect_to projects_path, notice: "Successfully destroyed"
	end

	private

	def project_param
		params[:project].permit(:name, :description, :start_date, :client_id, :status, category_ids: [] )
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h2>Edit Project</h2> 


<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<div class = "errors" style = "color: red;">
			<h3>These errors prohibitted the form from being saved: </h3>
			<ul>
				<% @project.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>
	<%= f.label :description %><br/>
	<%= f.text_area :description %><br/>
	<%= f.label :start_date %><br/>
	<%= f.date_select :start_date, order: [:day, :month, :year] %><br/>
	<%= f.label :client_id %><br/>
	<%= f.collection_select :client_id, current_user.clients, :id, :name, promot: "select client" %><br/>
	<!--
	<%= f.label :status %>
	<%= f.select :status, ["new", "on-going", "completed"], promot: "select status" %>
	-->
	<%= f.label :status %><br/>
	<%= f.radio_button :status, "new" %> New <br/>
	<%= f.radio_button :status, "on-going" %> On-going <br/>
	<%= f.radio_button :status, "completed" %> Completed <br/>
	<%= f.label :categories %><br/> 
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br/>

	<%= f.submit %>

<% end %>

app/views/projects/index.html.erb
<h2>List of projects</h2>

<%= link_to "Add new project", new_project_path %>

<ol>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project_path(project.id) %> </li>
	<% end %>
</ol>

app/views/projects/new.html.erb
<h2>Add new Project</h2> 


<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<div class = "errors" style = "color: red;">
			<h3>These errors prohibitted the form from being saved: </h3>
			<ul>
				<% @project.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>
	<%= f.label :description %><br/>
	<%= f.text_area :description %><br/>
	<%= f.label :start_date %><br/>
	<%= f.date_select :start_date, order: [:day, :month, :year] %><br/><br/>
	<%= f.label :client_id %><br/>
	<%= f.collection_select :client_id, current_user.clients, :id, :name, promot: "select client" %><br/>
	<!--
	<%= f.label :status %>
	<%= f.select :status, ["new", "on-going", "completed"], promot: "select status" %>
	-->
	<%= f.label :status %><br/>
	<%= f.radio_button :status, "new" %> New <br/>
	<%= f.radio_button :status, "on-going" %> On-going <br/>
	<%= f.radio_button :status, "completed" %> Completed <br/>
	<%= f.label :categories %><br/>
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br/>

	<%= f.submit %>

<% end %>

app/views/projects/show.html.erb
<h2>Project name : <%= @project.name %></h2> 
<b>Client name : <%= link_to @project.client.try(:name).capitalize	, client_path(@project.client) %><br/><br/>

<b>Categories : </b>
<ul>
	<% @project.categories.each do |category| %>
		<li><%= category.name %></li>
	<% end %> 
</ul>

<br/><br/>
<%= link_to "Edit", edit_project_path(@project.id) %> |
<%= link_to "Destroy", project_path(@project.id), method: :delete, data: {confirm: "Are you sure"}  %> |
<%= link_to "Back", projects_path %><br/><br/><br/>

<h2>Listing Tasks</h2>
<b>Over due</b>
<ol>
	<% @project.over_due_tasks.each do |task| %>
		<li><%= task.title %></li>
	<% end %>
</ol> 
<b>Incompleted</b>
<ol>
	<% @project.incompleted_tasks.each do |task| %>
		<li><%= task.title %></li>
	<% end %>
</ol>
<b>Completed</b>
<ol>
	<% @project.completed_tasks.each do |task| %>
		<li><%= task.title %></li>
	<% end %>
</ol>  
<br/><br/>


<%= form_for @task do |f| %>
	<%= f.label :title %><br/>
	<%= f.text_field :title %><br/>
	<%= f.label :due_date %><br/>
	<%= f.date_select :due_date %><br/>
	<%= f.label :is_completed %>? <br/>
	<%= f.check_box :is_completed %><br/>

	<%= f.hidden_field :project_id, value: @project.id %><br/>

	<%= f.submit %>


<% end %>