config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'sandbox/clients'

  get 'sandbox/projects'

  get 'sandbox/products'
  get 'say/listing_products'
  get 'say/goodbye'
  get 'say/hello'

  get '/sandbox/get_jobs'
  get '/sandbox/zomato'

  resources :clients
  resources :projects
  resources :tasks

   root 'projects#index'

end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController
  def clients
  	@clients = Client.all
  end

  def projects
  	@projects = Project.where('start_date > ? AND start_date < ?', Date.today.beginning_of_month-3.months,Date.today.beginning_of_month).order('start_date')
  end

  def products
=begin

    1. List all products based on a given category
    2. List products based on price range
    3. List products based on brand
    4. List products based on size of a certain brand falling within a given price range
    5. List products that are available
    6. List products following under price 499
    7. List products upto price 1200
    8. List all products based on the categories
    9. List only products which are available
    10. List products price descending and name ascending
    11. List products whose prices are the same as a group
    12. Display the total worth of the products
    13. Display total worth of products in each category
    14. List all products based on the categories


=end
	# 1
	@category = "Toys"
	@products_category = Product.where('category = ?', @category).limit(20)

	#2
	@price_range_min = 300
	@price_range_max = 500
	@products_price_range = Product.where('price >= ? AND price <= ?', @price_range_min, @price_range_max).limit(20)

	#3
	@brand = "Peter England"
	@products_brand = Product.where('brand = ?', @brand).limit(20)

	#4
	@size = "XL"
	@products_size = Product.where('size = ? AND brand = ? AND price >= ? AND price <= ?', @size, @brand, @price_range_min, @price_range_max).limit(20)

	#5
	@products_available = Product.where('availability = ? ', "t").limit(20)

	#6
	@price = 499
	@products_price = Product.where('price <= ?', @price).limit(20)

	#7
	@price = 999 
	@products_price_upto = Product.where('price <= ?', @price).limit(20)

	#8
	@category_product_hash = {}
	@products = Product.all.limit(20)
	@products.each do |product|
		if @category_product_hash.has_key? product.category 
			@category_product_hash[product.category].push(product.name)
		else
			#@category_product_hash[product.category] = []
			@category_product_hash[product.category] = [product.name]
		end
	end

	#9
	#same as 5th query

	#10
	@products 
	@price_name_order = @products.order('price DESC', 'name')


	#11
	@products = Product.all
	@price_group_hash = {}
	@products.each do |product|
		if @price_group_hash.has_key? product.price
			@price_group_hash[product.price].push(product.name)
		else
			@price_group_hash[product.price] = [product.name]
		end
	end
=begin
	@price_group_hash["0 - 25"] = @products.where('price >= ? AND price <= ?', 0, 25).limit(10)
	@price_group_hash["26 - 50"] = @products.where('price >= ? AND price <= ?', 26, 50).limit(10)
	@price_group_hash["51 - 75"] = @products.where('price >= ? AND price <= ?', 51, 75).limit(10)
	@price_group_hash["76 - 99"] = @products.where('price >= ? AND price <= ?', 76, 99).limit(10)
=end


	#12
	@total_worth = Product.sum(:price)
=begin
	@total_worth = 0
	@products = Product.all
	@products.each do |product|
		@total_worth += product.price
	end
=end
	#13
	@category_price_hash = {}
	@products = Product.all.limit(20)
	@products.each do |product|
		if @category_price_hash.has_key? product.category 
			@category_price_hash[product.category] += product.price
		else
			#@category_product_hash[product.category] = 0
			@category_price_hash[product.category] = product.price
		end
	end

	#14
	#same as query 8

	#15
	@category_hash = {}
	@products = Product.all
	@products.each do |product|
		if @category_hash.has_key? product.category 
			@category_hash[product.category]["names"].push(product.name)
			@category_hash[product.category]["total_worth"] += product.price
		else
			@category_hash[product.category] = {}
			@category_hash[product.category]["names"] = [product.name]
			@category_hash[product.category]["total_worth"] = product.price
		end
	end
end


def get_jobs

	if params[:technology]

		technology = params[:technology]
		location = params[:location]
		@response = HTTParty.get("http://api.indeed.com/ads/apisearch?publisher=7277146494571922&q=#{technology}&l=#{location}&co=india&format=json&v=2")

	end
end

def zomato



	end


end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/views/sandbox/clients.html.erb
<p2>List of clients</p2><br>
<p2>Total clients are <%= @clients.size %></p2>
<ol>
	<% @clients.each do |client| %>
	<li><%= client.name %> </li>


	<% end %>
</ol> 

app/views/sandbox/get_jobs.html.erb
<h3> search jobs </h3>



<%= form_tag({url: sandbox_get_jobs_path}, {method: :get}) do %>

    <%= label_tag :technology %><br/>
    <%= text_field_tag :technology %><br/>

    <%= label_tag :location %><br/>
    <%= text_field_tag :location %><br/>

    <%= submit_tag "Search..." %>

<% end %>

<% if !@response.nil? %>
<% response = @response.parsed_response %>

<h3>Jobs Found - <%= response["totalResults"] %></h3>

<ul>
    <% response["results"].each do |job| %>
    <li>
        <%= job["jobtitle"] %>---<%= job["company"] %>---<%= job["city"] %>
    </li>
    <% end %>
</ul>

<% end %>

app/views/sandbox/products.html.erb
<h2>1. List of products based on a given category "<%= @category %>"</h2>
<ol>
	<% @products_category.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>2. List of products based on price range <%= @price_range_min %> - <%= @price_range_max %></h2>
<ol>
	<% @products_price_range.each do |product| %>
		<li><%= product.name %> - Rs <%= product.price %></li>
	<% end %>
</ol>

<h2>3. List of products based on a given brand "<%= @brand %>"</h2>
<ol>
	<% @products_brand.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>4. List of products based on size of a certain brand falling within a given price range</h2><br>
<h3>Size - <%= @size %>, Brand - <%= @brand %>, Price range - <%= @price_range_min %>-<%= @price_range_max %></h3> 
<ol>
	<% @products_size.each do |product| %>
		<li><%= product.name %> - <%= product.brand %> - <%= product.size %> - <%= product.price %></li>
	<% end %>
</ol>

<h2>5. List of products that are available </h2>
<ol>
	<% @products_available.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>6. List of products following under price <%= @price %> </h2>
<ol>
	<% @products_price.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>7. List of products upto price <%= @price %> </h2>
<ol>
	<% @products_price_upto.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>8. List of products based on the categories </h2>
<ol>
	<% @category_product_hash.each do |category, names| %>
		<li><%= category %></li>
			<ol>
				<% names.each do |name| %>
					<li><%= name %></li>
				<% end %>
			</ol>
	<% end %>
</ol>

<h2>9. List of products that are available </h2>
<ol>
	<% @products_available.each do |product| %>
		<li><%= product.name %></li>
	<% end %>
</ol>

<h2>10. List of products price decending and name ascending</h2><br>
<h3>Price High-Low</h3>
<ol>
	<% @price_name_order.each do |product| %>
		<li><%= product.name %> - Rs <%= product.price %></li>
	<% end %>
</ol>

<h2>11. List products according to their price group</h2>
<ol>
	<% @price_group_hash.each do |price, names| %>
		<li>Price group Rs <%= price %></li>
		<ol>
			<% names.each do |name| %>
				<li><%= name %></li>
			<% end %>
		</ol>
	<% end %>
</ol>


<h2>12. The total worth of the products is <%= @total_worth %> </h2>

<h2>13. List of products based on the categories and their Total worth</h2>
<ol>
	<% @category_price_hash.each do |category, value| %>
	<li><%= category %>	<br>Total worth is Rs <%= value %></li>
	<% end %>
</ol>

<h2>15. List of products according to categories and their total worth</h2>
<ol>
	<% @category_hash.each do |category, value_hash| %>
		<li><%= category %></li>
		<ol>
		<% value_hash["names"].each do |name| %>
			<li><%= name %></li>
		<% end %>
		</ol>
		<b>Total worth is Rs <%= value_hash["total_worth"] %></b>
	<% end %>
</ol>

app/views/sandbox/projects.html.erb
<p2>Projects list</p2><br>
<p2>Total projects <%= @projects.size %></p2>
<ol>
	<% @projects.each do |project| %>
	<li><%= project.name %> - <%= project.start_date %></li>
	<% end %>
</ol>	

app/views/sandbox/zomato.html.erb
<% restaurant = JSON.parse('

{
  "R":
  	 {
    	"res_id": 51318
  		},
  
  "apikey": "bbaa7f2f778234292b1ace341832669b",
  
  "id": "51318",
 
  "name": "MTR 1924",
 
  "url": "https://www.zomato.com/bangalore/mtr-1924-st-marks-road?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
 
  "location": {
 
    "address": "29, Ground Floor, White House, St. Marks Road, Bangalore",
 
    "locality": "St. Marks Road",
    "city": "Bangalore",
    "city_id": 4,
    "latitude": "12.9723907156",
    "longitude": "77.6010814682",
    "zipcode": "0",
    "country_id": 1
  },
  "cuisines": "South Indian",
  "average_cost_for_two": 250,
  "price_range": 1,
  "currency": "Rs.",
  "offers": [],
  "thumb": "https://b.zmtcdn.com/data/pictures/8/51318/024d841c2d9a9ecfc0bbcfaf8139f42f_featured_v2.jpg",
  "user_rating": {
    "aggregate_rating": "4.1",
    "rating_text": "Very Good",
    "rating_color": "5BA829",
    "votes": "414"
  },
  "photos_url": "https://www.zomato.com/bangalore/mtr-1924-st-marks-road/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
  "menu_url": "https://www.zomato.com/bangalore/mtr-1924-st-marks-road/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
  "featured_image": "https://b.zmtcdn.com/data/pictures/8/51318/024d841c2d9a9ecfc0bbcfaf8139f42f_featured_v2.jpg",
  "has_online_delivery": 0,
  "is_delivering_now": 0,
  "deeplink": "zomato://restaurant/51318",
  "has_table_booking": 0,
  "events_url": "https://www.zomato.com/bangalore/mtr-1924-st-marks-road/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
}') %>

<% reviews = JSON.parse('
{
  "reviews_count": 201,
  "reviews_start": 0,
  "reviews_shown": 5,
  "user_reviews": [
    {
      "review": {
        "rating": 5,
        "review_text": "What an amazing food. Go there for breakfast and lunch. South Indian food feast . Only if you had a very huge tummy to fill the amazing food. Super cool. And service is amazing. Only issue was for lunch when we ask for the mango halwa second time dey hesitated 😅 but its ok I will still visit the place and recommend to everyone in Bangalore",
        "id": "28585597",
        "rating_color": "305D02",
        "review_time_friendly": "20 days ago",
        "rating_text": "Insane!",
        "timestamp": 1477579102,
        "likes": 3,
        "user": {
          "name": "Namitha Vikram",
          "foodie_level": "Big Foodie",
          "foodie_level_num": 5,
          "foodie_color": "ffae4f",
          "profile_url": "https://www.zomato.com/users/namitha-vikram-29155833?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "profile_image": "https://b.zmtcdn.com/data/user_profile_pictures/915/3fa3911eaa2c2a1437e7a4a19113d915.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A",
          "profile_deeplink": "zomato://u/29155833"
        },
        "comments_count": 0
      }
    },
    {
      "review": {
        "rating": 3,
        "review_text": "Ambience - average  Options - only south indian Taste - average  Service - Good  If you think all MTR branches are same this place makes you pondering. My taste buds just denied to accept it as MTR",
        "id": "28574282",
        "rating_color": "CDD614",
        "review_time_friendly": "21 days ago",
        "rating_text": "Average",
        "timestamp": 1477444854,
        "likes": 0,
        "user": {
          "name": "Prasanna S",
          "foodie_level": "Big Foodie",
          "foodie_level_num": 4,
          "foodie_color": "ffae4f",
          "profile_url": "https://www.zomato.com/users/prasanna-s-34932595?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "profile_image": "https://b.zmtcdn.com/data/user_profile_pictures/cec/23451cb1a8053d78be24c05717707cec.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A",
          "profile_deeplink": "zomato://u/34932595"
        },
        "comments_count": 0
      }
    },
    {
      "review": {
        "rating": 4.5,
        "review_text": "MTR does not need a review ( coz, it is that popular). My favorite here is Masala Dosa and Chandrahara (A must try).  Everything is tasty - Meals, Tiffins, sweets. Bisibella bath should be eaten when served hot. MTR is a must visit place every Sunday for us.",
        "id": "28402886",
        "rating_color": "3F7E00",
        "review_time_friendly": "one month ago",
        "rating_text": "Loved it!",
        "timestamp": 1475690145,
        "likes": 0,
        "user": {
          "name": "Siri K",
          "foodie_level": "Foodie",
          "foodie_level_num": 3,
          "foodie_color": "ffd35d",
          "profile_url": "https://www.zomato.com/users/siri-k-32272987?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "profile_image": "https://b.zmtcdn.com/data/user_profile_pictures/8c0/75f1253cd9a97b6bfc811cd9022498c0.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A",
          "profile_deeplink": "zomato://u/32272987"
        },
        "comments_count": 0
      }
    },
    {
      "review": {
        "rating": 4.5,
        "review_text": "I had the difficult task of taking my north indian friends to an authentic south Indian restaurant. It had to be good. It had to be extraordinary actually. Its a matter of pride. Then after all the brain storming, I knew that MTR would be a perfect place and it was. Ah the podi dosa....ok I am getting to it.  Location and ambience : Its located in both Commercial street and St Marks road. The interiors aint so pumped up but when the food is all that matters, we go blind na?!  Food : My northie...",
        "id": "28298295",
        "rating_color": "3F7E00",
        "review_time_friendly": "one month ago",
        "rating_text": "Loved it!",
        "timestamp": 1474647875,
        "likes": 8,
        "user": {
          "name": "Subhiksha Venkat",
          "zomato_handle": "Subhikshavenkat",
          "foodie_level": "Connoisseur",
          "foodie_level_num": 13,
          "foodie_color": "e95151",
          "profile_url": "https://www.zomato.com/Subhikshavenkat?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "profile_image": "https://b.zmtcdn.com/data/user_profile_pictures/08e/b3c19f9a34b41ad29f7d07a12751908e.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A",
          "profile_deeplink": "zomato://u/2887416"
        },
        "comments_count": 0
      }
    },
    {
      "review": {
        "rating": 4.5,
        "review_text": "Branch of an iconic place that is tucked in a silent lane of St.Marks Road. The place has no fancy boards to attract crowd however, I have never seen this place empty.   One of the best eateries to try authentic Bangalorean version of south Indian... The place serves most of their dishes with signature cup filled with ghee, making the food all the more delicious.   The place is one of my favourites, do try it once 😁  Recommendations - Masala Dosa, Onion Dosa and Rava Idli",
        "id": "28289708",
        "rating_color": "3F7E00",
        "review_time_friendly": "one month ago",
        "rating_text": "Loved it!",
        "timestamp": 1474557024,
        "likes": 1,
        "user": {
          "name": "Shwetha K.N",
          "zomato_handle": "shwethakn",
          "foodie_level": "Super Foodie",
          "foodie_level_num": 8,
          "foodie_color": "f58552",
          "profile_url": "https://www.zomato.com/shwethakn?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
          "profile_image": "https://b.zmtcdn.com/data/user_profile_pictures/bfe/1044e5585352895ec62b3c1172d3abfe.jpg?fit=around%7C100%3A100&crop=100%3A100%3B%2A%2C%2A",
          "profile_deeplink": "zomato://u/176402"
        },
        "comments_count": 0
      }
    }
  ],
  "Respond to reviews via Zomato Dashboard": "https://www.zomato.com/business/claim?ref=rpg&resid=51318#claim"
}')

%>

<br/>
<%= restaurant["name"] %><br/>

<%= link_to "visit", restaurant["url"] %>
<%= image_tag(restaurant["thumb"]) %><br/>

<h3>Address</h3>
<%= restaurant["location"]["address"] %>

<h3>Cuisines</h3>
<%= restaurant ["cuisines"] %>

<h3>cost for 2</h3>
<%=restaurant["average_cost_for_two"] %>

<h3> Menu</h3> <br/>
<%= link_to "MENU",restaurant["menu_url"] %>

<h3>Phone Numbers</h3>
<%=restaurant["phone_numbers"] %> <br/>

<h3>Restaurant reviews</h3> 
<b> total reviews </b> <%= reviews["reviews_count"] %> <br/>
<% reviews["user_reviews"].each do |rew| %> 

<%= image_tag(rew["review"]["user"]["profile_image"]) %>---<%= rew["review"]["user"]["name"] %>------------<%= rew["review"]["user"]["foodie_level"] %><br/>
<%= rew["review"]["review_text"] %> <br/>
<%= rew["review"]["rating_text"] %> <br/>
<%= rew["review"]["review_time_friendly"] %> <br/>
<% end %>